image: python:3.12

stages:
  - install
  - test

before_script:
  - pip install poetry  # 安装最新的 Poetry

install_dependencies:
  stage: install
  script:
    - poetry config virtualenvs.create false  # 在项目目录中安装依赖
    - poetry install  # 安装依赖

run_tests:
  stage: test
  script:
    - poetry run pytest  # 使用 Poetry 运行测试
  artifacts:
    paths:
      - test-results/  # 如果你有测试结果需要保存，可以修改这里
    expire_in: 1 week  # 指定工件过期时间
