image: python:3.12

stages:
  - install
  - test

install_dependencies:
  stage: install
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 -  # 安装 Poetry
    - export PATH="$HOME/.local/bin:$PATH"                     # 添加 Poetry 到 PATH
  script:
    - poetry install

run_tests:
  stage: test
  script:
    - poetry run pytest  # 使用 Poetry 运行测试
